name: Secrets 
on:
  push:
    branches: [ main ]
jobs:
  GGShield:
    name: GGSheild 
    runs-on: ubuntu-latest
    env:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker
        run: |
          echo "hello world"
